bilibilipro:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    host: localhost
    port: 3306
    database: bilibilipro
    username: root # your username
    password: 123456 #your password
  alioss:
    endpoint: oss-cn-beijing.aliyuncs.com
    access-key-id: XXXXXXXX # your keyId
    access-key-secret: XXXXXXXXX # your keySecret
    bucket-name: bilibilipropost #your bucket name
  redis:
    host: localhost
    port: 6379
    password: 123456 #your password
    database: 0
