bilibilipro:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    host: 43.138.245.107
    port: 3306
    database: bilibilipro
    username: root
    password: Wcy674648
  alioss:
    endpoint: oss-cn-beijing.aliyuncs.com
    access-key-id: LTAI5tSNp2vFSMDr66Sq9jUT
    access-key-secret: m45MvpQQvYVjLoolF9C0hk2j3phSkn
    bucket-name: bilibilipropost
  redis:
    host: 43.138.245.107
    port: 6379
    password: Wcy674648
    database: 0
